
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.common.services.ws;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-10-05T00:11:11.316-05:00
 * Generated source version: 2.4.2
 * 
 */
public class ValidadorCFDClient {

    public static void main(String[] args) throws Exception {
        QName serviceName = new QName("http://ws.services.common.org/", "ValidadorCFDImplService");
        QName portName = new QName("http://ws.services.common.org/", "ValidadorCFDImplPort");

        Service service = Service.create(serviceName);
        service.addPort(portName, SOAPBinding.SOAP11HTTP_BINDING,
        		"http://localhost:8080/RecepcionFacturas/services/ValidadorCFDImplPort"); 
        org.common.services.ws.ValidadorCFD client = service.getPort(portName,  org.common.services.ws.ValidadorCFD.class);
		File xmlFi = new File("C:/Users/lwong/Desktop/FA.xml");
		
		InputStream is = new FileInputStream(xmlFi);
		ByteArrayOutputStream bos = new ByteArrayOutputStream();
		byte[] b = new byte[1024];
		int bytesRead;
		while (( bytesRead = is.read(b) ) != -1) {
		   bos.write(b, 0, bytesRead);
		}
		byte[] bytes = bos.toByteArray();
		System.out.println(new String(bytes,"UTF8"));
		
        client.validaXML(bytes, new Integer(1));
        // Insert code to invoke methods on the client here
    }

}