
package org.common.services.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.2
 * Wed Oct 05 00:11:09 CDT 2011
 * Generated source version: 2.4.2
 */

@XmlRootElement(name = "validaXMLResponse", namespace = "http://ws.services.common.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "validaXMLResponse", namespace = "http://ws.services.common.org/")

public class ValidaXMLResponse {

    @XmlElement(name = "return")
    private java.util.List<org.common.services.xml.Error> _return;

    public java.util.List<org.common.services.xml.Error> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<org.common.services.xml.Error> new_return)  {
        this._return = new_return;
    }

}

